name: ADMT

on:
  push:
    branches:
      - main

jobs:
  copy-to-prod:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create prod directory
      run: mkdir -p prod
    - name: Copy file to prod
      run: |
        cp dev/test.txt prod/test.txt
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Copy test.txt to prod"
        commit_user_name: "GitHub Actions"
        commit_user_email: "actions@github.com"
    
  copy-confirmation:
    runs-on: ubuntu-latest
    needs: copy-to-prod
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line confirmation
        run: echo File Copied!
